### ISSUE TITLE
403 Forbidden error invoking postPermissionSetData

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#35]
After following the workshop to configure this project and Postman (using the provided Postman project and an environment I created), I receive the error that the PermissionSetCallerRole does not have permission to call `execute-api:Invoke` on the API endpoint. 

Inspecting the API Gateway endpoints in the Target account, I see the `env-permissionSetApi` and the `env-linkApi` have no resource policy configured (it's blank). I added a resource policy for the principal `arn:aws:iam:(target account id):role/PermissionSetCallerRole` to perform the action `execute-api:Invoke` on the resource `arn:aws:execute-api:us-east-1:(target account id):(gateway domain name random string)/*/*/*` and now the API call works.

If I try the link API, I get the same error with LinkCallerRole.

Questions:

- Is the API supposed to be accessible with no Resource Policy set on the API Gateway endpoints?
- Is the deployment of this project *supposed* to create a Resource Policy on the API Gateway endpoints?
- If a Resource Policy is not used, what mechanism provides permissions for the API Gateway endpoints to be invoked?

Info:

- I'm using *one* region everywhere (us-east-1) with *two* distinct accounts in total. Everything is in the Org Main account except for the "Target Account", which is a member of the organization. Target is a separate account mainly because the current release fails to deploy with a single account and region for the entire project (see my other GitHub issue).

I am not sure if this is a bug or a configuration issue on my end.

**Comment by leelalagudu** [comment]
Hi @allquixotic  , 

Can you confirm these 2 questions please? 
- Have you run [this step](https://catalog.us-east-1.prod.workshops.aws/v2/workshops/640b0bab-1f5e-494a-973e-4ed7919d397b/en-US/01-deployment/100-sourcecode#step-3:-create-execution-roles) as part of preparation?  
- In your config/env.yaml , values for `LinkCallerRoleArn` and `PermissionSetCallerRoleArn` - are they correct?

This is how the solution sets up the access for API end points:

- When you choose "api" as the interface mode for either `LinksProvisioningMode` or `PermissionSetProvisioningMode` , then the solution takes the role arn for link caller and/or permission set caller and grant this role with `execute-api:Invoke` permissions on the resource `arn:aws:execute-api:us-east-1:(target account id):(gateway domain name random string)/*/*/*` 
- This would then allow you to use IAM authorisation as explained [here](https://catalog.us-east-1.prod.workshops.aws/v2/workshops/640b0bab-1f5e-494a-973e-4ed7919d397b/en-US/02-api/200-postman) to call the API end points for processing your account assignments and permission sets
- API gateway resource policies are additionally required when you want to restrict caller scope to a user from a specific end point / specific source IP address or CIDR blocks / specific VPC's or VPC end points. This is not the case with our solution. We intentionally design the authorisation mechanism to be IAM driven , so that if the caller has the correct AWS STS credentials generated, they would then be able to call the API end point.

Hope this clarifies your question. Let us know if you have any follow up questions.

**Comment by allquixotic** [comment]
> In your config/env.yaml , values for LinkCallerRoleArn and PermissionSetCallerRoleArn - are they correct?

I had neglected to update these when switching from using the same target account as OrgMain, over to a separate target account. I checked them into CodeCommit and the CodePipelines ran...

 > This would then allow you to use IAM authorisation as explained here and here to call the API end points for processing your account assignments and permission sets

Ah, it's IAM driven, not resource policy driven. The permissions policies for the `PermissionSetCallerRole` and `LinksCallerRole` were empty when I had the Role ARNs wrong - that's why I was confused. Now I see an inline policy attached to the caller roles.

 > API gateway resource policies are additionally required only when you want to restrict caller scope to a user from a specific AWS account / specific source IP address or CIDR blocks / specific VPC's or VPC end points. This is not the case with our solution. We intentionally designed the authorisation mechanism to be IAM driven , so that if the caller has the correct AWS STS credentials generated, they would then be able to call the API end point from anywhere.

I guess we were using a weird workaround by enabling resource policies by hand, due to the misconfiguration issue in env.yaml.

Now that I've got this working with a separate target account and the resource policy workaround removed, I'm going to re-test the fix to the other issue you worked on for me. Thanks!
