### ISSUE TITLE
OrgMain account not affected by root.all?

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#39]
Hi,

In S3 provisioning mode, if I create a file in links_data like this:

`root.all.Admin-ps.Admins.GROUP.ssofile`

This causes all the member accounts to get the permission set `Admin-ps` for the `Admins` group.

However, the _Org Main_ account (the master payer account) does not receive this change. In fact, I have never observed SSO Extensions touching the settings of the Org Main account in the AWS SSO console at all.

Is this intended? Can it be overridden if this is intended behavior? I realize it could be dangerous to affect SSO settings of the master payer account, but we have IAM and (if necessary) root account credentials for it, so we won't be able to lock ourselves out of our account using SSO Extensions. We can always recover from whatever settings we apply.

**Comment by leelalagudu** [comment]
Hi @allquixotic  ,

This is a limitation with not our solution but AWS SSO admin API. Using AWS SSO admin API, you can't programmatically assign/remove a permission set to _OrgMain_ account. The API does not allow this operation, as it's a fail safe implemented by the service directly.

This is why our solution skips _OrgMain_ account in any `root` scope type operations. 

Please let me know if you need any other details.

**Comment by allquixotic** [comment]
Thanks for the information. I am good with closing this issue, but my only suggestion might be to mention this prominently in README.md. I'll leave it open in case you want to reference this issue in a doc change PR.

Thanks again!

**Comment by leelalagudu** [comment]
Thank you for the feedback @allquixotic  , we will reference this in the doc updates PR

**Comment by leelalagudu** [comment]
PR #41  fixes the missing documentation, and since the functionality originates from a hard restriction on the service API, I am going ahead and closing the issue for now @allquixotic . 

At a later time, when AWS SSO does allow operating permission sets/account assignments through API on org main account, then we would adapt the code to handle this. For reference, this is a [single if condition](https://github.com/aws-samples/aws-sso-extensions-for-enterprise/blob/main/lib/lambda-functions/application-handlers/src/linkManager.ts#L116) that would be commented out, and the solution would then start treating org main account as any other account.
