### ISSUE TITLE
3.0.3 upgrade fails

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#51]
Hi,

An upgrade from 3.0.2 to 3.0.3 failed in the codepipeline `envawsssoextensionsforenter`

It failed in CDK Synth:

`Error: UpgradeFromVersionLessThanV303 does not exist or is of not the correct data type`.

Let me know if you need more context.

**Comment by leelalagudu** [comment]
Hi @allquixotic , 

Thank you for raising this issue. This is occurring because we introduced an additional config parameter in 3.0.3 called `UpgradeFromVersionLessThanV303` . Could you update your config file to match the `config\env.yaml` sample file in terms of keys and retry please? Also, could you set the `UpgradeFromVersionLessThanV303` parameter to `true` as you are upgrading from earlier versions and the account assignment data would need to be upgraded to the new convention i.e. move from dot(.) to percent(%). 

Additionally, we would like to understand if our release notes (for v3.0.3 - https://github.com/aws-samples/aws-sso-extensions-for-enterprise/releases/tag/v3.0.3) are easy to understand and follow. Could you help us with any feedback that would help us improve/change how we write our release notes?

Thank you,
Leela

**Comment by allquixotic** [comment]
That fixed everything except for FileAsset21, which failed with

```
Action execution failed
Error calling startBuild: Cannot have more than 20 builds in queue for the account (Service:  AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException
```

**Comment by allquixotic** [comment]
> Additionally, we would like to understand if our release notes (for v3.0.3 - https://github.com/aws-samples/aws-sso-extensions-for-enterprise/releases/tag/v3.0.3) are easy to understand and follow. Could you help us with any feedback that would help us improve/change how we write our release notes?

The release notes are clear. I _did not see them_ before, which is the reason I didn't follow them. Had I seen them, this issue probably wouldn't have occurred. Thank you.

**Comment by leelalagudu** [comment]
> That fixed everything except for FileAsset21, which failed with
> 
> ```
> Action execution failed
> Error calling startBuild: Cannot have more than 20 builds in queue for the account (Service:  AWSCodeBuild; Status Code: 400; Error Code: AccountLimitExceededException
> ```

This is due to your account hitting the concurrent build quota limit as described [here](https://docs.aws.amazon.com/codebuild/latest/userguide/limits.html). 
Trigger for reaching the concurrent builds quota limit is due to the number of lambda functions we have deployed as part of the solution. CDK pipeline deployment does the packaging of each lambda function (transpiled TS code along with dependencies) as a separate and concurrent build job in the `build` stage of the pipeline. With the new lambda functions we added as part of v3.0.3(around format changing), you are hitting this no. 
Once the quota limit increase self service request is complete on your account, you could then proceed with `release change` on the pipeline and this should successfully pass the `build` stage.

**Comment by leelalagudu** [comment]
> Also, `env-aws-sso-extensions-for-enterprise-upgradeToV303Stack.Prepare` and `env-aws-sso-extensions-for-enterprise-upgradeToV303Stack.Deploy` are "Didn't Run" status. That is strange.
> 
> As a result, my links_data are still in the old format. Maybe they didn't run because the asset failed?

Yep, because the build stage has failed the pipeline effectively stopped. Once you have redeployed the pipeline by clicking on `release change` after the quota increase is in place, this would trigger the stack deployment and your links_data would then be upgraded to the new format

**Comment by allquixotic** [comment]
My AWS CodeBuild Concurrently Running Builds quota limit is at the default of 60 according to the Service Quotas dashboard. Why does the error say 20? Is this the correct quota to request?

Also, is there any way to modify the SSOEx solution so that it doesn't fire off so many concurrent builds, so that a quota increase isn't necessary?

**Comment by leelalagudu** [comment]
> My AWS CodeBuild Concurrently Running Builds quota limit is at the default of 60 according to the Service Quotas dashboard. Why does the error say 20? Is this the correct quota to request?
> 
> Also, is there any way to modify the SSOEx solution so that it doesn't fire off so many concurrent builds, so that a quota increase isn't necessary?

`Cannot have more than x builds in the queue` is a symptom of exceeding the concurrent build quota, so we are looking at the correct quota limit increase. Could you retry by `releasing the change` on the pipeline and see if the `build` stage goes through ? 
Regarding the parallel build jobs trigger, it speeds up the pipeline deployment to parallelise any build job where feasible and this is one of those scenarios where it would be more optimal to parallelise them instead of running the build jobs serially. Additionally, given that we use CDK's native pipeline construct, this is the default behaviour i.e. the `build` stage is defined by the construct itself. We could look at an escape hatch route to control this, but for the reasons mentioned previously, we would prefer this to be parallel.

**Comment by allquixotic** [comment]
Releasing the change caused the build to fail again, only with a different file artifact. I've opened a support ticket with AWS business support under the category of CodeBuild to have them identify which limit is being hit. It doesn't make sense that the error says 20 but my quota (the default quota for all AWS accounts) is 60, so I'm asking them to clarify.

**Comment by allquixotic** [comment]
AWS support said "For some platforms and compute types, the default is 20." and linked me to https://docs.aws.amazon.com/codebuild/latest/userguide/limits.html#service-quotas

I still don't understand where this number of 20 is coming from. The other question is, if the default limit is 60, what number should I request in my quota increase to get SSOEx to build successfully?

None of this makes any sense still. I'm completely confused.

**Comment by leelalagudu** [comment]
> AWS support said "For some platforms and compute types, the default is 20." and linked me to https://docs.aws.amazon.com/codebuild/latest/userguide/limits.html#service-quotas
> 
> I still don't understand where this number of 20 is coming from. It isn't listed anywhere in the documentation. The other question is, if the default limit is 60, what number should I request in my quota increase to get SSOEx to build successfully when it seems only to require about 25 concurrent builds (out of the "60" I have available)?
> 
> None of this makes any sense still. I'm completely confused.

I am confused as well @allquixotic . Few of our team mates had this exact issue and raising the quota limit for conurrent builds fixed it for us. At this point of time, other than asking you to follow up with AWS support, unfortunately I don't have an answer that helps with the issue.

**Comment by allquixotic** [comment]
After receiving the quota increase for concurrent builds, everything in CodePipeline/CodeBuild works, and I no longer receive the error emails when trying to add users/groups that already exist via SCIM API.

**Comment by leelalagudu** [comment]
Hi @allquixotic ,

@jmejco  did some research on this and observed that the speed advantage we would gain through parallel builds for asset publishing is being nullified by the code build instance provisioning lag across the 20 concurrent build jobs that are being triggered for packaging all lambda assets. As this is not adding any advantage from a speed perspective, we've reverted this behaviour i.e. disable the parallel trigger and instead force the pipeline to specifically use one code build job for packaging all lambda assets. This behaviour is now the default from [v3.1.1](https://github.com/aws-samples/aws-sso-extensions-for-enterprise/releases/tag/v3.1.1).
