### ISSUE TITLE
Does SSOEx hit AWSOrganizations API regularly?

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-sso-extensions-for-enterprise#57]
Hi,

We are doing a proof of concept of AWS Firewall Manager in the same OrgMain account as our SSOEx solution (which is deployed in a single-region, single-account configuration).

We notice that AWS Firewall Manager sometimes faces errors with the AWS Organizations API such as:

```
Unable to enable sharing with AWS Organizations. 
Received TooManyRequestsException from AWSOrganizations with the following error message: AWS Organizations can't complete your request because another request is already in progress. Try again later.
```

In trying to root cause why we're being rate limited, we wondered if SSOEx might be hitting AWS Organizations often. Does any ongoing / scheduled code in SSOEx use the Organizations API?

How about if we do SCIM operations against AWS SSO? In that case, do the Lambda triggers resulting from that perform any Organizations API calls?

To be clear, this is a question, not a defect - trying to understand product behavior as part of a troubleshooting session.

**Comment by leelalagudu** [comment]
Hi @allquixotic,

The solution hits Organizations API in only this scenario: when you had a link created with a `root` or `ou_id` scope value. When such a link is created, the solution triggers a state machine to resolve the target accounts list and this is only triggered  when the permission set and the principal (user/group) referred in the link exists. This operation is also triggered only once for provisioning the link payload.

SCIM operations being done would trigger the solution calling AWS Identity Store API to resolve the GUID's for the username/group display name i.e. they don't trigger the Organizations API.

With regards to the no of times the Organizations API is invoked by the solution, you could look in your orgmain account us-east-1 region and see the number of runs the step function `env-processTargetAccountSM` is run. This is the maximum no of times the solution may have hit the Organizations API. I say maximum, because this state machine is triggered for `root`, `ou_id` and `account_tag` scopes , however Organizations API is only called for `root` and `ou_id` scopes only.

Hope this helps clarify. Do let us know if you have any other questions

**Comment by leelalagudu** [comment]
Hi @allquixotic , following up on this  - do you need any other info from our end around this question?
